### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by spontoreau** [gvinsot/SilverScript#6]
TSLint return a huge number of errors, let's start to fix them :)

Goal: 0 lint errors.

**Comment by gvinsot** [comment]
Oh oh how big is it ?  I'll work on that next week, wife and children not at home !

**Comment by spontoreau** [comment]
Install npm packages and use the lint script:
npm run lint

To be honest i didn't count errors, but there are many little errors (i think 75% are just conventions)
